[package]
name = "esbuild-rs"
version = "0.0.1"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"
include = ["/src/**/*", "/build.rs", "/Cargo.toml", "/libesbuild.a", "/libesbuild.h"]

[dependencies]
