name: Build demo

on: push

jobs:
  demo:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.0'
      - name: Build demo
        working-directory: ./demo
        run: cargo build --release -vvv
